---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.6

suites:
  - name: default
    run_list:
      - recipe[t3-mailhog::install]
# testing uninstall is not that easy, as all resource declarations would be merged..
#  - name: uninstall
#    run_list:
#      - recipe[t3-mailhog::install]
#      - recipe[t3-mailhog::uninstall]
